### ISSUE TITLE
An error with duplex reads

### ISSUE THREAD

**Issue by andreyurch** [Psy-Fer/blue-crab#6]
Dear developer,

I tried to use blue-crab with Remora test files and encountered the following error with their duplex reads:
blue-crab p2s duplex_reads.pod5 -o duplex.blow5
01-Sep-23 12:14:11 - blue-crab - [INFO]: single2single: 1 pod5 file detected as input. Writing 1:1 pod5->s/blow5 to file: duplex.blow5
01-Sep-23 12:14:11 - blue-crab - [INFO]: opening slow5 file: duplex.blow5
01-Sep-23 12:14:11 - blue-crab - [INFO]: s2s: Reading pod5 file: duplex_reads.pod5
01-Sep-23 12:14:12 - blue-crab - [INFO]: Writing header - limited to 1 read group for now, split your pod5 if it's a merged file
01-Sep-23 12:14:12 - blue-crab - [INFO]: Slow5 header written
01-Sep-23 12:14:12 - blue-crab - [ERROR]: acquisition_id does not match prev value: 0: 1205f0ff5922a968dcfbdeb51ff68ecffe7fa4df 1: 2262db6c2c5ed9c0e1db04d4f5d9582a1cec7876
01-Sep-23 12:14:12 - blue-crab - [ERROR]: More than 1 read_group present - split your pod5
01-Sep-23 12:14:12 - blue-crab - [ERROR]: Error encounted, exiting.

Is it expected?  With their nonduplex reads everything worked well:
blue-crab p2s can_reads.pod5 -o can_reads.blow5

01-Sep-23 11:57:14 - blue-crab - [INFO]: single2single: 1 pod5 file detected as input. Writing 1:1 pod5->s/blow5 to file: can_reads.blow5
01-Sep-23 11:57:14 - blue-crab - [INFO]: opening slow5 file: can_reads.blow5
01-Sep-23 11:57:14 - blue-crab - [INFO]: s2s: Reading pod5 file: can_reads.pod5
01-Sep-23 11:57:14 - blue-crab - [INFO]: Writing header - limited to 1 read group for now, split your pod5 if it's a merged file
01-Sep-23 11:57:14 - blue-crab - [INFO]: Slow5 header written
01-Sep-23 11:57:14 - blue-crab - [INFO]: pod5 -> s/blow5 complete

**Comment by Psy-Fer** [comment]
Hey,

Is your pod5 file from multiple runs?

The error is complaining about multiple rub_id/acquisition_id being present which usually indicates multiple runs being merged. This means you need multiple headers to account for that.

Try splitting your reads by acquisition_id and try again. You can then merge the separate blow5 files again and it will merge the headers by making multiple read_groups.


Duplex data is just normal data. There isn't anything special inside the pod5 files.

Let me know how you go or if you need more explicit instructions.

Cheers,
James.
