### ISSUE TITLE
ERROR : acquistion_id does not match prev value

### ISSUE THREAD

**Issue by biozzq** [Psy-Fer/blue-crab#8]
Dear all,

I used the following commands to convert the pod5 files located in pod5_pass directory to one blow5 file,
`blue-crab p2s -t 8 pod5_pass -o merge.blow5`, however, an error occurred to me as follows.

```
29-Oct-23 08:59:49 - blue-crab - [INFO]: many2single: 669 pod5 files detected as input. Writing many pod5 to one s/blow5 file: merge.blow5
29-Oct-23 08:59:49 - blue-crab - [INFO]: opening slow5 file: merge.blow5
29-Oct-23 08:59:53 - blue-crab - [INFO]: m2s: Reading 669 pod5 file/s
29-Oct-23 08:59:53 - blue-crab - [INFO]: Writing header - limited to 1 read group for now, split your pod5 if it's a merged file
29-Oct-23 08:59:53 - blue-crab - [INFO]: Slow5 header written
29-Oct-23 09:22:48 - blue-crab - [ERROR]: acquisition_id does not match prev value: 0: aee96a6c0d849d8fd19740b2da55516a038f36ad 1: b06100f7621a3d6c0fba8a8ab82440aab5b26535
29-Oct-23 09:22:48 - blue-crab - [ERROR]: More than 1 read_group present - split your pod5
29-Oct-23 09:22:48 - blue-crab - [ERROR]: Error encounted, exiting.
```
Any suggestion will be greatly appreciated. Thank you very much.

Sincerely,
Zheng zhuqing

**Comment by hasindu2008** [comment]
Hi
Could you please try `blue-crab p2s -p 8 pod5_pass -d slow5_pass` which performs a one-to-one POD->BLOW5 conversion and see if the error persists? If that works, you can perform a `slow5tools merge -t8 slow5_pass/ -o merge.blow5` to create single merged BLOW5 file. I am trying to see if it is a single POD5 file with multiple run_ids causing the problem or if it is just this error message is misleading.

**Comment by biozzq** [comment]
It works when performing a one-to-one pod->blow5 conversion. Thank you very much.

**Comment by hasindu2008** [comment]
Thanks for reporting this too. That error message is confusing for this case and @Psy-Fer will fix it in the next release.
